const TitleLogin = () => {
    return ( 
        <div className="flex flex-col items-center justify-center">
            <h1 className="text-5xl font-bold text-center text-white">
                Netflix Clone
            </h1>
            <p className="text-center text-white">
                Generated by GusDev
            </p>
        </div>
     );
}
 
export default TitleLogin;